version: 2
updates:
  - package-ecosystem: github-actions
    target-branch: dev
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    target-branch: dev
    directory: /
    open-pull-requests-limit: 20
    versioning-strategy: increase
    schedule:
      interval: weekly
      time: "09:00"
      timezone: Europe/Paris
    ignore:
      # Manually update major versions of @types/node with the version specified within .nvmrc
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
