catalog:
  "@ai-sdk/openai": 3.0.29
  "@ai-sdk/react": 3.0.92
  "@base-ui/react": 1.2.0
  "@biomejs/biome": 2.4.2
  "@commitlint/cli": 20.4.1
  "@commitlint/config-conventional": 20.4.1
  "@nivalis/biome-config": 2.4.2
  "@prisma/adapter-neon": 7.4.0
  "@prisma/client": 7.4.0
  "@tailwindcss/postcss": 4.1.18
  "@total-typescript/ts-reset": 0.6.1
  "@types/node": 22.18.13
  "@types/react": 19.2.14
  "@types/react-dom": 19.2.3
  "@vercel/analytics": 1.6.1
  "@vercel/blob": 2.2.0
  "@vercel/config": 0.0.31
  ai: 6.0.90
  babel-plugin-react-compiler: 1.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  date-fns: 4.1.0
  dotenv: 17.3.1
  embla-carousel-react: 8.6.0
  input-otp: 1.4.2
  lefthook: 2.1.1
  lucide-react: 0.574.0
  next: 16.1.6
  next-themes: 0.4.6
  postcss: 8.5.6
  prisma: 7.4.0
  react: 19.2.4
  react-day-picker: 9.13.2
  react-dom: 19.2.4
  react-resizable-panels: 4.6.4
  recharts: 3.7.0
  schema-dts: 1.1.5
  server-only: 0.0.1
  sonner: 2.0.7
  tailwind-merge: 3.4.1
  tailwindcss: 4.1.18
  turbo: 2.8.9
  typescript: 5.9.3
  vaul: 1.1.2
  workflow: 4.1.0-beta.57
  zod: 4.3.6

onlyBuiltDependencies:
  - "@nestjs/core"
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@swc/core"
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - bufferutil
  - cbor-extract
  - esbuild
  - lefthook
  - msw
  - prisma
  - protobufjs
  - puppeteer
  - sharp
