catalog:
  '@ai-sdk/openai': 3.0.12
  '@ai-sdk/react': 3.0.40
  '@base-ui/react': 1.1.0
  '@biomejs/biome': 2.3.11
  '@commitlint/cli': 20.3.1
  '@commitlint/config-conventional': 20.3.1
  '@nivalis/biome-config': 2.3.11
  '@prisma/adapter-neon': 7.2.0
  '@prisma/client': 7.2.0
  '@tailwindcss/postcss': 4.1.18
  '@total-typescript/ts-reset': 0.6.1
  '@types/node': 22.18.13
  '@types/react': 19.2.8
  '@types/react-dom': 19.2.3
  '@vercel/analytics': 1.6.1
  '@vercel/blob': 2.0.0
  '@vercel/config': 0.0.25
  ai: 6.0.38
  babel-plugin-react-compiler: 1.0.0
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  dotenv: 17.2.3
  lefthook: 2.0.15
  lucide-react: 0.562.0
  next: 16.1.2
  postcss: 8.5.6
  prisma: 7.2.0
  react: 19.2.3
  react-dom: 19.2.3
  schema-dts: 1.1.5
  server-only: 0.0.1
  tailwind-merge: 3.4.0
  tailwindcss: 4.1.18
  tailwindcss-animate: 1.0.7
  turbo: 2.7.4
  typescript: 5.9.3
  workflow: 4.0.1-beta.48
  zod: 4.3.5

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - bufferutil
  - esbuild
  - lefthook
  - prisma
  - protobufjs
  - puppeteer
  - sharp
