onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - bufferutil
  - esbuild
  - lefthook
  - prisma
  - protobufjs
  - puppeteer
  - sharp
