onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - "@vercel/speed-insights"
  - bufferutil
  - esbuild
  - lefthook
  - prisma
  - protobufjs
  - puppeteer
  - sharp

catalog:
  "babel-plugin-react-compiler": "1.0.0"
  "class-variance-authority": "0.7.1"
  "clsx": "2.1.1"
  "lucide-react": "0.552.0"
  "next": "16.0.1"
  "postcss": "8.5.6"
  "react": "19.2.0"
  "react-dom": "19.2.0"
  "server-only": "0.0.1"
  "tailwind-merge": "3.3.1"
  "turbo": "2.6.0"
  "zod": "4.1.12"
  "@biomejs/biome": "2.3.2"
  "@commitlint/cli": "20.1.0"
  "@commitlint/config-conventional": "20.0.0"
  "@nivalis/biome-config": "2.3.2"
  "@tailwindcss/postcss": "4.1.16"
  "@total-typescript/ts-reset": "0.6.1"
  "@types/node": "22.2.0"
  "@types/react": "19.2.2"
  "@types/react-dom": "19.2.2"
  "lefthook": "2.0.2"
  "tailwindcss": "4.1.16"
  "tailwindcss-animate": "1.0.7"
  "typescript": "5.9.3"
