import '@/styles/globals.css';
import { fonts } from '@/fonts';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='en'>
      <body className={fonts}>{children}</body>
    </html>
  );
};

export default RootLayout;
